### ISSUE TITLE
Refactor tablefill and textfill

### ISSUE THREAD

**Issue by z-y-huang** [gentzkow/gslab_make#16]
Goals:

1. Port `tablefill` and `textfill` for Python 3
2. Refactor `tablefill` and `textfill` to make codebase more Pythonic and transparent

I would focus on completing (1) then moving on to (2). I had started on (1) with [this commit](https://github.com/gentzkow/gslab_make/commit/3171dfaddc633d6934881b6d9e69b890df3b1f51) but never actually tested to see if everything was working correctly on Python 3.

I would branch off [issue13_template_to_dos](https://github.com/gentzkow/gslab_make/tree/issue13_template_to_dos).

**Comment by jc-cisneros** [comment]
### Summary

The goal of this issue was to `Port tablefill and textfill for Python 3`. Per [this comment](https://github.com/gslab-econ/gslab_make/pull/30#issuecomment-1636447142) and the decisions in https://github.com/gslab-econ/gslab_make/pull/30#issuecomment-1636587464 and https://github.com/gslab-econ/gslab_make/pull/30#issuecomment-1636825918, we did not merge any changes to master.

 Find an stable link to the last version of the development branch [here](https://github.com/gslab-econ/gslab_make/tree/6a2976ba95b81c3826adc2fce015e6602852b1ed).

As an extra note in case this issue needs to be revisited, in the [PR for this issue](https://github.com/gslab-econ/gslab_make/pull/30#issue-631134002) it was mentioned that "textfill has been deprioritized as we have a new method for filling in scalars in LyX documents".
